/controller_manager:
  base_controller:
    ros__parameters:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel: 'wheel_left_joint'
      right_wheel: 'wheel_right_joint'
      publish_rate: 50.0
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      enable_odom_tf: false
      odom_frame_id: "world"
      base_frame_id: "base_link"
      wheel_separation: 0.19
      wheel_radius: 0.050
      wheel_separation_multiplier: 1.0
      wheel_radius_multiplier: 1.0
      publish_cmd: false
      cmd_vel_timeout: 0.5
      allow_multiple_cmd_vel_publishers: true
      linear:
        x:
          has_velocity_limits: true
          max_velocity: 0.60
          min_velocity: -0.60
          has_acceleration_limits: true
          max_acceleration: 2.6
          min_acceleration: -2.6
      angular:
        z:
          has_velocity_limits: true
          max_velocity: 3.1
          has_acceleration_limits: true
          max_acceleration: 2.6
